# -*- coding: utf-8 -*-
"""Analisis de ventas

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/181Iq-qfUwR-ac8vtCGN_GTK70lVZofxy

# ANALISIS DE VENTAS

## dataframe
"""

import numpy as np
import pandas as pd

# generando datos aleatorios para tres productos
ventas_producto_a = np.random.randint(50, 1000, size=100)
ventas_producto_b = np.random.randint(30, 800, size=100)
ventas_producto_c = np.random.randint(20, 600, size=100)

# creando un indice con los dias de la semana
dias = ['Lunes', 'Martes', 'Miercoles', 'Jueves', 'Viernes']
indice = np.random.choice(dias, size=100)

# creando un DataFrame a partir de los datos generados
data = {
    'Producto A': ventas_producto_a,
    'Producto B': ventas_producto_b,
    'Producto C': ventas_producto_c
}

df = pd.DataFrame(data, index=indice)

# mostrando el dataframe
df

"""## ventas totales"""

# calculando ventas totales de cada producto durante la semana
ventas_totales_producto_a = df['Producto A'].groupby(df.index).sum()
ventas_totales_producto_b = df['Producto B'].groupby(df.index).sum()
ventas_totales_producto_c = df['Producto C'].groupby(df.index).sum()

# mostrando las ventas totales de cada producto
print("Ventas totales del Producto A:")
print(ventas_totales_producto_a)
print("\nVentas totales del Producto B:")
print(ventas_totales_producto_b)
print("\nVentas totales del Producto C:")
print(ventas_totales_producto_c)

"""## dia en que se vendió mas cada producto"""

# encontrando el día en que se vendió más de cada producto
dia_max_venta_producto_a = df['Producto A'].groupby(df.index).sum().idxmax()
dia_max_venta_producto_b = df['Producto B'].groupby(df.index).sum().idxmax()
dia_max_venta_producto_c = df['Producto C'].groupby(df.index).sum().idxmax()

# mostrando los días en que se vendió más de cada producto
print("Día con más ventas para el Producto A: ", dia_max_venta_producto_a)
print()
print("Día con más ventas para el Producto B: ", dia_max_venta_producto_b)
print()
print("Día con más ventas para el Producto C: ", dia_max_venta_producto_c)
print()

"""## promedio de ventas de cada producto"""

# calculando el promedio de ventas diarias de cada producto
prom_ventas_producto_a = df['Producto A'].groupby(df.index).mean()
prom_ventas_producto_b = df['Producto B'].groupby(df.index).mean()
prom_ventas_producto_c = df['Producto C'].groupby(df.index).mean()

# mostrando el promedio de ventas diarias de cada producto
print("Promedio de ventas diarias del Producto A:")
print(prom_ventas_producto_a)
print("\nPromedio de ventas diarias del Producto B:")
print(prom_ventas_producto_b)
print("\nPromedio de ventas diarias del Producto C:")
print(prom_ventas_producto_c)

"""## productos con menor venta en un dia"""

# encontrando el producto con la menor cantidad de ventas en un dia
producto_min_venta = df.idxmin(axis=1)
cantidad_min_venta = df.min(axis=1)

# mostrando el producto con la menor cantidad de ventas en un día
for idx, row in enumerate(df.iterrows()):
    dia = row[0]
    producto = producto_min_venta[idx]
    cantidad = cantidad_min_venta[idx]
    print(f"En {dia}, el producto con menor venta fue {producto} con {cantidad} unidades.")

"""## grafico de ventas diarias"""

import matplotlib.pyplot as plt

# graficando las ventas diarias de cada producto
plt.figure(figsize=(10, 6))
df.groupby(df.index)['Producto A'].sum().plot(label='Producto A')
df.groupby(df.index)['Producto B'].sum().plot(label='Producto B')
df.groupby(df.index)['Producto C'].sum().plot(label='Producto C')

plt.title('Ventas Diarias')
plt.xlabel('Día de la semana')
plt.ylabel('Ventas')
plt.legend()
plt.grid()
plt.show()